version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jira_clone_db
    environment:
      POSTGRES_USER: jira_user
      POSTGRES_PASSWORD: jira_password
      POSTGRES_DB: jira_clone
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U jira_user -d jira_clone']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
